#!/bin/sh
master_branch='master'
candidate_branch='candidate'
develop_branch='develop'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# only run this if you are pushing to master
if [[ $current_branch -eq $master_branch || $current_branch -eq $candidate_branch || $current_branch -eq $develop_branch ]] ; then
    
    echo -e "${YELLOW}Running pre push to ${current_branch} check...${NC}"
    echo -e "${YELLOW}Trying to build projects...${NC}"

    dotnet build

    rc=$?
    if [[ $rc != 0 ]] ; then
        echo -e "${RED}Failed to build the project, please fix this and push again${NC}"
        echo ""
        exit $rc
    fi

    for d in tests/*/; do
        echo -e "Running tests in ${d}"

        dotnet test $d

        rc=$?

        if [[ $rc != 0 ]] ; then
            echo -e "${RED}Unit tests failed, please fix and push again${NC}"
            echo ""
            exit $rc
        fi

    done
    
fi

echo -e "${GREEN}Pre push check passed!${NC}"
echo ""

exit 0